Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'spec/codebreaker/validator_spec.rb'
  Max: 120

Metrics/BlockLength:
  Exclude: 
    - 'spec/codebreaker/game_spec.rb'
    - 'codebracker_gem.gemspec'
