---
:users_statistic:
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 4
  hints: 2
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 3
  hints: 1
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 1
  hints: 2
- !ruby/object:Statistic
  name: Ivan
  difficulty: Hell
  attempts: 4
  hints: 1
- !ruby/object:Statistic
  name: Ivan
  difficulty: Medium
  attempts: 4
  hints: 0
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 4
  hints: 0
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 4
  hints: 0
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 4
  hints: 0
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 4
  hints: 0
- !ruby/object:Statistic
  name: Ivan
  difficulty: Easy
  attempts: 4
  hints: 0
